### ISSUE TITLE
Implement text field

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#103]
This structure seems to be mandatory:
```html
<div class="input-field">
  <input placeholder="Placeholder" id="first_name" type="text" class="validate">
  <label for="first_name">First Name</label>
</div>
```

The IDs are also mandatory, unfortunately.
So I propose a custom element:
```html
<md-input md-validate="true"></md-input>
```

This allows for generated IDs and providing the above mentioned structure automatically.

For text areas we could either use an option for ```md-input``` or provide a separate element.

**Comment by Thanood** [comment]
Input labels seem to be displayed a little too much to the right. This is also the case with original Materialize input fields. Their websites displays [how it should be](https://www.google.com/design/spec/components/text-fields.html#text-fields-labels), though.

**Comment by Thanood** [comment]
Can be fixed like this:
```css
md-input .input-field label {
  transform: translateX(-10%);
}
md-input .input-field label.active {
  transform: translateX(-10%) translateY(-140%);
}
```
