### ISSUE TITLE
flat (unmodified) buttons don't have a "hover" animation

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-materialize-bridge#34]
As can be seen on the button sample page, a flat button (```md-button="flat: true;"```) doesn't have a hover animation. A large button has that animation.

In addition to that, a disabled flat button gets the "focus" style when clicked on. A disabled raised button does not. Also, regular and large buttons (not flat) are animated differently on hover,

This may be a Materialize issue or may be caused by mixing Bootstrap and Materialize. Will have to check again when Bootstrap can be removed.

**Comment by Thanood** [comment]
Most likely a Materialize bug. It's fixable by using this css:
```css
.btn-flat:hover {
    background-color: #2bbbad;
    transition: .2s ease-out;
}
```
